//
//  Conformance.h
//  xtypes-interop
//
//  Created by Kelvin Zhang on 6/8/18.
//
#ifndef __CONFORMANCE_HEADER
#define __CONFORMANCE_HEADER

#ifndef RTI_DDS_PRO
#define RTI_DDS_PRO
#endif
#define WRITER_RESOURCE_LIMITS_SUPPORTED 0
#define READER_RESOURCE_LIMITS_SUPPORTED 0
#define DATA_REPRESENTATION_QOS_SUPPORTED 0
#define QOS_STRING_PROPERTY_SUPPORTED 1
#define PARTICIPANT_REGISTRY_SUPPORTED 0
#define DISCOVERY_SETNAME_SUPPORTED 0
#define MAX_PORT_QOS_SUPPORTED 0
#define MAX_LOCAL_TYPE_QOS_SUPPORTED 0
#define RESOURCE_LIMIT_QOS_IS_FLAT 0
#define HAS_MAX_PARTICIPANTS_LIMIT 0
#define COMPONENT_FACTORY_SUPPORTED 0
#define DATABASE_QOS_SUPPORTED 1
#define DISCOVERY_CONFIG_SUPPORTED 1
#define TYPE_CONSISTENCY_QOS_SUPPORTED 0
#define TRANSPORTS_QOS_SUPPORTED 0
#define USER_TRAFFIC_QOS_SUPPORTED 0
#define FLAT_DATA_SUPPORTED 1
#endif
