
enum MessageType
{
	TEST_ACTION_EXIT,
    TEST_ACTION_WRITE_CDR_QOS,
	TEST_ACTION_WRITE_CDR,
	TEST_ACTION_WRITE_EXTENSIBILITY_KIND,
	TEST_ACTION_WRITE_SERIALIZATION,
    TEST_ACTION_WRITE_SECURITY,
    TEST_ACTION_WRITE_FLATDATA,
    TEST_ACTION_WRITE_ZEROCOPY,
	TEST_INFO_INIT_DONE,
	TEST_INFO_ACK
};

enum CDRPolicy
{
	CDR_POLICY_XCDR,
	CDR_POLICY_XCDR2,
	CDR_POLICY_XCDR_XCDR2
};

enum CDRQosTest {
    T1_XCDR__XCDR,
    T1_XCDR__XCDR2,
    T1_XCDR__XCDR_XCDR2,
    T1_XCDR2__XCDR,
    T1_XCDR2__XCDR_XCDR2,
    T1_XCDR2__XCDR2
};

enum CDRTest {
    T1_XCDR2_FLAT_SHMEM_REF,
    T2_XCDR2_FLAT_SHMEM_REF,
    T3_XCDR2_FLAT_SHMEM_REF,
    T4_XCDR2_FLAT_INBAND,
    T5_XCDR2_FLAT_INBAND,
    T6_XCDR2_FLAT_INBAND,
    T7_XCDR2_FLAT_SHMEM_REF_INBAND,
    T8_XCDR2_FLAT_SHMEM_REF_INBAND,
    T9_XCDR2_FLAT_SHMEM_REF_INBAND,
    T10_XCDR2_PLAIN_SHMEM_REF,
    T11_XCDR2_PLAIN_SHMEM_REF,
    T12_XCDR2_PLAIN_SHMEM_REF,
    T13_XCDR2_PLAIN_INBAND,
    T14_XCDR2_PLAIN_INBAND,
    T15_XCDR2_PLAIN_INBAND,
    T16_XCDR2_PLAIN_INBAND_SHMEM_REF,
    T17_XCDR2_PLAIN_INBAND_SHMEM_REF,
    T18_XCDR2_PLAIN_INBAND_SHMEM_REF,
    T19_XCDR2_PLAIN_SHMEM_REF,
    T20_XCDR2_PLAIN_SHMEM_REF,
    T21_XCDR2_PLAIN_SHMEM_REF,
    T22_XCDR2_PLAIN_SHMEM_REF,
    T23_XCDR2_PLAIN_SHMEM_REF,
    T24_XCDR2_PLAIN_SHMEM_REF,
    T25_XCDR2_PLAIN_INBAND,
    T26_XCDR2_PLAIN_INBAND,
    T27_XCDR2_PLAIN_INBAND,
    T28_XCDR2_PLAIN_INBAND,
    T29_XCDR2_PLAIN_INBAND,
    T30_XCDR2_PLAIN_INBAND,
    T31_XCDR2_PLAIN_INBAND_SHMEM_REF,
    T32_XCDR2_PLAIN_INBAND_SHMEM_REF,
    T33_XCDR2_PLAIN_INBAND_SHMEM_REF,
    T34_XCDR2_PLAIN_INBAND_SHMEM_REF,
    T35_XCDR2_PLAIN_INBAND_SHMEM_REF,
    T36_XCDR2_PLAIN_INBAND_SHMEM_REF
};

enum ExtensibilityKind
{
    T4_2_1_SHAPE1FINAL_SHAPE1FINAL,
    T4_2_1_SHAPE1FINAL_SHAPE1APPENDABLE,
    T4_2_1_SHAPE1FINAL_SHAPE1MUTABLE,
    T4_2_1_SHAPE1FINAL_SHAPE1DEFAULT,
    T4_2_1_SHAPE1APPENDABLE_SHAPE1APPENDABLE,
    T4_2_1_SHAPE1APPENDABLE_SHAPE1MUTABLE,
    T4_2_1_SHAPE1APPENDABLE_SHAPE1DEFAULT,
    T4_2_1_SHAPE1MUTABLE_SHAPE1MUTABLE,
    T4_2_1_SHAPE1MUTABLE_SHAPE1DEFAULT,


    T4_2_2_SHAPE1FINAL_SHAPE2FINAL,
    T4_2_2_SHAPE1APPENDABLE_SHAPE2APPENDABLE,
    T4_2_2_SHAPE1MUTABLE_SHAPE2MUTABLE,
    T4_2_2_SHAPE1FINAL_SHAPE2FINAL_PREVENT_WIDENING,
    T4_2_2_SHAPE1APPENDABLE_SHAPE2APPENDABLE_PREVENT_WIDENING,
    T4_2_2_SHAPE1MUTABLE_SHAPE2MUTABLE_PREVENT_WIDENING,
    T4_2_2_SHAPE2FINAL_SHAPE1FINAL_PREVENT_WIDENING,
    T4_2_2_SHAPE2APPENDABLE_SHAPE1APPENDABLE_PREVENT_WIDENING,
    T4_2_2_SHAPE2MUTABLE_SHAPE1MUTABLE_PREVENT_WIDENING,

    T4_2_4_SHAPE1FINAL_SHAPE4FINAL,
    T4_2_4_SHAPE1APPENDABLE_SHAPE4APPENDABLE,
    T4_2_4_SHAPE1MUTABLE_SHAPE4MUTABLE,
    T4_2_4_SHAPE1MUTABLEEXPLICITID_SHAPE4MUTABLEEXPLICITID,


    T4_2_5_SHAPE2FINAL_SHAPE5FINAL,
    T4_2_5_SHAPE2APPENDABLE_SHAPE5APPENDABLE,
    T4_2_5_SHAPE2MUTABLE_SHAPE5MUTABLE,


    T4_2_6_SHAPE1FINAL_SHAPE6FINAL,
    T4_2_6_SHAPE1APPENDABLE_SHAPE6APPENDABLE,
    T4_2_6_SHAPE1MUTABLE_SHAPE6MUTABLE,
    T4_2_6_SHAPE6FINAL_SHAPE1FINAL,
    T4_2_6_SHAPE6APPENDABLE_SHAPE1APPENDABLE,
    T4_2_6_SHAPE6MUTABLE_SHAPE1MUTABLE,
    T4_2_6_SHAPE1FINAL_SHAPE6FINAL_IGNORE_STRING_BOUNDS,
    T4_2_6_SHAPE1APPENDABLE_SHAPE6APPENDABLE_IGNORE_STRING_BOUNDS,
    T4_2_6_SHAPE1MUTABLE_SHAPE6MUTABLE_IGNORE_STRING_BOUNDS,
    T4_2_6_SHAPE6FINAL_SHAPE1FINAL_IGNORE_STRING_BOUNDS,
    T4_2_6_SHAPE6APPENDABLE_SHAPE1APPENDABLE_IGNORE_STRING_BOUNDS,
    T4_2_6_SHAPE6MUTABLE_SHAPE1MUTABLE_IGNORE_STRING_BOUNDS,


    T4_2_7_SHAPE1FINAL_SHAPE7FINAL,
    T4_2_7_SHAPE1APPENDABLE_SHAPE7APPENDABLE,
    T4_2_7_SHAPE1MUTABLE_SHAPE7MUTABLE,
    T4_2_7_SHAPE7FINAL_SHAPE1FINAL,
    T4_2_7_SHAPE7APPENDABLE_SHAPE1APPENDABLE,
    T4_2_7_SHAPE7MUTABLE_SHAPE1MUTABLE,
    T4_2_7_SHAPE1FINAL_SHAPE7FINAL_IGNORE_SEQUENCE_BOUNDS,
    T4_2_7_SHAPE1APPENDABLE_SHAPE7APPENDABLE_IGNORE_SEQUENCE_BOUNDS,
    T4_2_7_SHAPE1MUTABLE_SHAPE7MUTABLE_IGNORE_SEQUENCE_BOUNDS,
    T4_2_7_SHAPE7FINAL_SHAPE1FINAL_IGNORE_SEQUENCE_BOUNDS,
    T4_2_7_SHAPE7APPENDABLE_SHAPE1APPENDABLE_IGNORE_SEQUENCE_BOUNDS,
    T4_2_7_SHAPE7MUTABLE_SHAPE1MUTABLE_IGNORE_SEQUENCE_BOUNDS,


    T4_2_8_SHAPE1FINAL_SHAPE8FINAL_IGNORE_MEMBER_NAME,
    T4_2_8_SHAPE1APPENDABLE_SHAPE8APPENDABLE_IGNORE_MEMBER_NAME,
    T4_2_8_SHAPE1MUTABLE_SHAPE8MUTABLE_IGNORE_MEMBER_NAME,
    T4_2_8_SHAPE1FINAL_SHAPE8FINAL,
    T4_2_8_SHAPE1APPENDABLE_SHAPE8APPENDABLE,
    T4_2_8_SHAPE1MUTABLE_SHAPE8MUTABLE,


    T4_2_9_SHAPE1FINAL_SHAPE9FINAL,
    T4_2_9_SHAPE1APPENDABLE_SHAPE9APPENDABLE,
    T4_2_9_SHAPE1MUTABLE_SHAPE9MUTABLE,


    T4_2_10_SHAPE1FINAL_SHAPE10FINAL,
    T4_2_10_SHAPE1APPENDABLE_SHAPE10APPENDABLE,
    T4_2_10_SHAPE1MUTABLE_SHAPE10MUTABLE,
    T4_2_10_SHAPE10FINAL_SHAPE1FINAL,
    T4_2_10_SHAPE10APPENDABLE_SHAPE1APPENDABLE,
    T4_2_10_SHAPE10MUTABLE_SHAPE1MUTABLE,


    T4_2_11_PARAMETER1FINAL_PARAMETER3FINAL,
    T4_2_11_PARAMETER1APPENDABLE_PARAMETER3APPENDABLE,
    T4_2_11_PARAMETER1MUTABLE_PARAMETER3MUTABLE,

    T4_2_12_PARAMETER1FINAL_PARAMETER2FINAL,
    T4_2_12_PARAMETER1APPENDABLE_PARAMETER2APPENDABLE,
    T4_2_12_PARAMETER1MUTABLE_PARAMETER2MUTABLE,

    T4_2_13_PARAMETER1FINAL_PARAMETER4FINAL,
    T4_2_13_PARAMETER1APPENDABLE_PARAMETER4APPENDABLE,
    T4_2_13_PARAMETER1MUTABLE_PARAMETER4MUTABLE,

    T4_2_14_PARAMETER4FINAL_PARAMETER5FINAL,
    T4_2_14_PARAMETER4APPENDABLE_PARAMETER5APPENDABLE,
    T4_2_14_PARAMETER4MUTABLE_PARAMETER5MUTABLE,
    T4_2_14_PARAMETER4FINAL_PARAMETER6FINAL,
    T4_2_14_PARAMETER4APPENDABLE_PARAMETER6APPENDABLE,
    T4_2_14_PARAMETER4MUTABLE_PARAMETER6MUTABLE,

    T4_2_15_SHAPE1FINAL_SHAPE11FINAL,
    T4_2_15_SHAPE1APPENDABLE_SHAPE11APPENDABLE,
    T4_2_15_SHAPE1MUTABLE_SHAPE11MUTABLE
};

enum SerializationTest {
	T5_2_1_SHAPE1FINAL_SHAPE1FINAL,
	T5_2_1_SHAPE1APPENDABLE_SHAPE1APPENDABLE,
	T5_2_1_SHAPE1APPENDABLE_SHAPE1DEFAULT,
	T5_2_1_SHAPE1MUTABLE_SHAPE1MUTABLE,

	T5_2_2_SHAPE1APPENDABLE_SHAPE2APPENDABLE,
	T5_2_2_SHAPE1MUTABLE_SHAPE2MUTABLE,
	T5_2_2_SHAPE2APPENDABLE_SHAPE1APPENDABLE,
	T5_2_2_SHAPE2MUTABLE_SHAPE1MUTABLE,

	T5_2_3_SHAPE1APPENDABLE_SHAPE3APPENDABLE,
	T5_2_3_SHAPE1MUTABLE_SHAPE3MUTABLE,
	T5_2_3_SHAPE3APPENDABLE_SHAPE1APPENDABLE,
	T5_2_3_SHAPE3MUTABLE_SHAPE1MUTABLE,

	T5_2_4_SHAPE1MUTABLEEXPLICITID_SHAPE4MUTABLEEXPLICITID,
	T5_2_4_SHAPE4MUTABLEEXPLICITID_SHAPE1MUTABLEEXPLICITID,

	T5_2_5_SHAPE2FINAL_SHAPE5FINAL,
	T5_2_5_SHAPE2APPENDABLE_SHAPE5APPENDABLE,
	T5_2_5_SHAPE2MUTABLE_SHAPE5MUTABLE,
	T5_2_5_SHAPE5FINAL_SHAPE2FINAL,
	T5_2_5_SHAPE5APPENDABLE_SHAPE2APPENDABLE,
	T5_2_5_SHAPE5MUTABLE_SHAPE2MUTABLE,

	T5_2_6_SHAPE1FINAL_SHAPE6FINAL,
	T5_2_6_SHAPE1APPENDABLE_SHAPE6APPENDABLE,
	T5_2_6_SHAPE1MUTABLE_SHAPE6MUTABLE,
	T5_2_6_SHAPE6FINAL_SHAPE1FINAL,
	T5_2_6_SHAPE6APPENDABLE_SHAPE1APPENDABLE,
	T5_2_6_SHAPE6MUTABLE_SHAPE1MUTABLE,

	T5_2_7_SHAPE1FINAL_SHAPE6FINAL,
	T5_2_7_SHAPE1APPENDABLE_SHAPE6APPENDABLE,
	T5_2_7_SHAPE1MUTABLE_SHAPE6MUTABLE,
	T5_2_7_SHAPE6FINAL_SHAPE1FINAL,
	T5_2_7_SHAPE6APPENDABLE_SHAPE1APPENDABLE,
	T5_2_7_SHAPE6MUTABLE_SHAPE1MUTABLE,

	T5_2_8_PARAMETER1FINAL_PARAMETER3FINAL,
	T5_2_8_PARAMETER1APPENDABLE_PARAMETER3APPENDABLE,
	T5_2_8_PARAMETER1MUTABLE_PARAMETER3MUTABLE,
	T5_2_8_PARAMETER3FINAL_PARAMETER1FINAL,
	T5_2_8_PARAMETER3APPENDABLE_PARAMETER1APPENDABLE,
	T5_2_8_PARAMETER3MUTABLE_PARAMETER1MUTABLE,

	T5_2_9_PARAMETER1APPENDABLE_PARAMETER2APPENDABLE,
	T5_2_9_PARAMETER1MUTABLE_PARAMETER2MUTABLE,
	T5_2_9_PARAMETER2APPENDABLE_PARAMETER1APPENDABLE,
	T5_2_9_PARAMETER2MUTABLE_PARAMETER1MUTABLE,

	T5_2_10_PARAMETER1APPENDABLE_PARAMETER7APPENDABLE,
	T5_2_10_PARAMETER1MUTABLE_PARAMETER7MUTABLE,
	T5_2_10_PARAMETER7APPENDABLE_PARAMETER1APPENDABLE,
	T5_2_10_PARAMETER7MUTABLE_PARAMETER1MUTABLE,

	T5_2_11_PARAMETER1APPENDABLE_PARAMETER4APPENDABLE,
	T5_2_11_PARAMETER1MUTABLE_PARAMETER4MUTABLE,
	T5_2_11_PARAMETER4APPENDABLE_PARAMETER1APPENDABLE,
	T5_2_11_PARAMETER4MUTABLE_PARAMETER1MUTABLE,

	T5_2_12_SHAPE1FINAL_SHAPE1FINAL,
	T5_2_12_SHAPE1APPENDABLE_SHAPE1APPENDABLE,
	T5_2_12_SHAPE1MUTABLE_SHAPE1MUTABLE,

	T5_2_13_A_SHAPE1MUTABLE_SHAPE11MUTABLE,
	T5_2_13_B_SHAPE1MUTABLE_SHAPE11MUTABLE,
	T5_2_13_C_SHAPE11MUTABLE_SHAPE1MUTABLE
};

struct TestNumAndPolicy {
	SerializationTest testNum;
	CDRPolicy policy;
};

enum SecurityTest
{
    T2_1_Allow_Unauth_Secure_Secure,
    T2_2_Secure_Secure,
    T2_3_Allow_Unauth_Secure_NonSecure,
    T2_4_Secure_NonSecure,
    T2_5_Allow_Unauth_Secure_NonSecure,
    T2_5_NonSecure_Topic,

    T3_1_RSA_DH,
    T3_2_RSA_ECDH,
    T3_3_DSA_DH,
    T3_4_DSA_ECDH,
    T3_5_ECDSA_DH,
    T3_6_ECDSA_ECDH,

    T3_7_RSA_DH,
    T3_8_RSA_ECDH,
    T3_9_DSA_DH,
    T3_10_DSA_ECDH,
    T3_11_ECDSA_DH,
    T3_12_ECDSA_ECDH,

    T3_13_RSA_DH,
    T3_14_RSA_ECDH,
    T3_15_DSA_DH,
    T3_16_DSA_ECDH,
    T3_17_ECDSA_DH,
    T3_18_ECDSA_ECDH,

    T3_19_Mismatched_Encryption,
    T3_20_Mismatched_Signing,
    T3_21_Mismatched_Key_Agreement,

    T4_1_Not_Common_CA,

    T5_1_RSA,
    T5_1_RSA_Impersonate,
    T5_2_DSA,
    T5_3_ECDSA,
    T5_4_ECDSA_Allow_Unauthenticated,

    T6_3_Liveliness_Lost,
    T6_4_Insecure_Liveliness_Assertions,

    T7_1_Encrypt__Encrypt,
    T7_2_Sign__Sign,
    T7_3_Encrypt_Sign__Encrypt,
    T7_4_Encrypt_Sign__Sign,
    T7_5_Encrypt__Encrypt_Sign,
    T7_6_Sign__Encrypt_Sign,

    T8_1_Domain_Rules_Mismatch,
    T8_2_Topic_Rules_Mismatch,

    T9_1_Max_Blocks_0,
    T9_2_Max_Blocks_5,
    T9_3_Max_Blocks_50,
    T9_4_Max_Blocks_500,
    T9_5_Max_Blocks_Foo,

    T11_1_Mismatch_Allowed_Domain,
    T11_2_Mismatch_Allowed_Topic,
    T11_3_Default_Rule,
    T11_4_Join_Access_Control,

    T12_1_Good_CA,

    T13_1_Certificate_Revocation
};

enum FlatDataTest {
    TFlat_To_Flat,
    TFlat_To_Plain,
    TPlain_To_Flat,
    TOffset_Test,
    TKeyed_Instance
};

enum ZeroCopyTest {
    T1_1_Fix_Size_Struct,
    T1_2_Variable_Size_Struct,
    T1_SHMEM_REF__FLAT,
    T2_SHMEM_REF__FLAT,
    T3_SHMEM_REF__FLAT,
    T4_SHMEM_REF__FLAT,
    T5_SHMEM_REF__PLAIN,
    T6_SHMEM_REF__PLAIN,
    T7_SHMEM_REF__PLAIN,
    T8_SHMEM_REF__PLAIN,
    T9_INBAND__FLAT,
    T10_INBAND__FLAT,
    T11_INBAND__FLAT,
    T12_INBAND__FLAT,
    T13_INBAND__PLAIN,
    T14_INBAND__PLAIN,
    T15_INBAND__PLAIN,
    T16_INBAND__PLAIN,
    T17_INBAND_SHMEM_REF__FLAT,
    T18_INBAND_SHMEM_REF__FLAT,
    T19_INBAND_SHMEM_REF__PLAIN,
    T20_INBAND_SHMEM_REF__PLAIN,
    T21_INBAND__FLAT,
    T22_INBAND__FLAT,
    T23_INBAND__FLAT,
    T24_INBAND__FLAT,
    T25_INBAND__PLAIN,
    T26_INBAND__PLAIN,
    T27_INBAND__PLAIN,
    T28_INBAND__PLAIN,
    T29_SHMEM_REF__FLAT,
    T30_SHMEM_REF__FLAT,
    T31_SHMEM_REF__FLAT,
    T32_SHMEM_REF__FLAT,
    T33_SHMEM_REF__PLAIN,
    T34_SHMEM_REF__PLAIN,
    T35_SHMEM_REF__PLAIN,
    T36_SHMEM_REF__PLAIN,
    T37_INBAND__FLAT,
    T38_INBAND__FLAT,
    T39_INBAND__FLAT,
    T40_INBAND__FLAT,
    T41_INBAND__PLAIN,
    T42_INBAND__PLAIN,
    T43_INBAND__PLAIN,
    T44_INBAND__PLAIN,
    T45_SHMEM_REF__FLAT,
    T46_SHMEM_REF__FLAT,
    T47_SHMEM_REF__FLAT,
    T48_SHMEM_REF__FLAT,
    T49_SHMEM_REF__PLAIN,
    T50_SHMEM_REF__PLAIN,
    T51_SHMEM_REF__PLAIN,
    T52_SHMEM_REF__PLAIN
};

union TestParam switch(MessageType) {
    case TEST_ACTION_WRITE_CDR_QOS:
        CDRQosTest cdrQosTest;
	case TEST_ACTION_WRITE_CDR:
		CDRTest cdrTest;
	case TEST_ACTION_WRITE_EXTENSIBILITY_KIND:
		ExtensibilityKind kind;
	case TEST_ACTION_WRITE_SERIALIZATION:
		TestNumAndPolicy testConfig;
    case TEST_ACTION_WRITE_SECURITY:
        SecurityTest securityTest;
    case TEST_ACTION_WRITE_FLATDATA:
        FlatDataTest flatDataTest;
    case TEST_ACTION_WRITE_ZEROCOPY:
        ZeroCopyTest zeroCopyTest;
	default:
		long not_used;
};

struct ControlMessage {
	MessageType action;
	TestParam param1;
};

